version: "3.9"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: teambuild
      POSTGRES_PASSWORD: teambuildpass
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local