version: "3.9"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: teambuild
      POSTGRES_PASSWORD: teambuildpass
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  application:
    build: .
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
volumes:
  db:
    driver: local